[config]
caching = true
contrast = 0.0

[config.wallpaper]
set = true
command = "awww img --transition-type fade --transition-duration 2 '{{ image }}'"

[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland-colors.lua"
output_path = "~/.config/hypr/colors.lua"
post_hook = "hyprctl reload"

[templates.hyprlock]
input_path = "~/.config/matugen/templates/hyprland-colors.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.waybar]
input_path = "~/.config/matugen/templates/colors.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "/usr/sbin/pkill -SIGUSR2 waybar || true"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi-colors.rasi"
output_path = "~/.config/rofi/themes/colors.rasi"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty-colors.conf"
output_path = "~/.config/kitty/themes/Matugen.conf"
post_hook = "kitty +kitten themes --reload-in=all Matugen"

[templates.dunst]
input_path = "~/.config/matugen/templates/dunstrc-colors"
output_path = "~/.config/dunst/dunstrc"
post_hook = "dunstctl reload"

[templates.gtk3]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-3.0/colors.css"
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-dark'

[templates.gtk4]
input_path = "~/.config/matugen/templates/gtk-colors.css"
output_path = "~/.config/gtk-4.0/colors.css"
post_hook = "~/.config/matugen/post-hook-scripts/gtk-themes-reload.sh"

[templates.papirus-folders]
input_path = '~/.config/matugen/templates/papirus-color'
colors_to_compare = [
    { name = "black",      color = "#4f4f4f" },
    { name = "blue",       color = "#5294e2" },
    { name = "bluegrey",   color = "#607d8b" },
    { name = "brown",      color = "#ae8e6c" },
    { name = "carmine",    color = "#a30002" },
    { name = "cyan",       color = "#00bcd4" },
    { name = "darkcyan",   color = "#45abb7" },
    { name = "deeporange", color = "#eb6637" },
    { name = "green",      color = "#87b158" },
    { name = "grey",       color = "#8e8e8e" },
    { name = "indigo",     color = "#5c6bc0" },
    { name = "magenta",    color = "#ca71df" },
    { name = "nordic",     color = "#81a1c1" },
    { name = "orange",     color = "#ee923a" },
    { name = "palebrown",  color = "#d1bfae" },
    { name = "paleorange", color = "#eeca8f" },
    { name = "pink",       color = "#f06292" },
    { name = "red",        color = "#e25252" },
    { name = "teal",       color = "#16a085" },
    { name = "violet",     color = "#7e57c2" },
    { name = "white",      color = "#e4e4e4" },
    { name = "yaru",       color = "#676767" },
    { name = "yellow",     color = "#f9bd30" },
]
compare_to = "{{ colors.primary.default.hex }}"
post_hook = 'sudo -n /usr/sbin/papirus-folders -C {{ closest_color }} -u'
index = 1

[templates.zathura]
input_path = "~/.config/matugen/templates/zathura-colors"
output_path = "~/.config/zathura/zathurarc"

[templates.kvantum_kvconfig]
input_path = "~/.config/matugen/templates/kvantum-colors.kvconfig"
output_path = "~/.config/Kvantum/matugen/matugen.kvconfig"

[templates.kvantum_svg]
input_path = "~/.config/matugen/templates/kvantum-colors.svg"
output_path = "~/.config/Kvantum/matugen/matugen.svg"

[templates.neovim]
input_path = "~/.config/matugen/templates/neovim/template.lua"
output_path = "~/.config/nvim/generated.lua"
post_hook = "/usr/sbin/pkill -SIGUSR1 nvim || true"

[templates.opencode]
input_path = "~/.config/matugen/templates/opencode-colors.json"
output_path = "~/.config/opencode/themes/matugen.json"

[templates.vscode-raw]
input_path = '~/.config/matugen/templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = "~/.config/matugen/templates/vscode-colors.json"
output_path = "~/.cache/matugen/vscode-colors.json"

[templates.zed]
input_path = "~/.config/matugen/templates/zed-colors.json"
output_path = "~/.config/zed/themes/matugen.json"

[templates.btop]
input_path = '~/.config/matugen/templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'
post_hook = 'pkill -USR2 btop || true'

[templates.xfce4-terminal]
input_path = '~/.config/matugen/templates/xfce4-terminal'
output_path = '/tmp/matugen-xfce4-terminal'
post_hook = "~/.config/matugen/post-hook-scripts/apply-xfce4-colors.sh"

[templates.tmux]
input_path = '~/.config/matugen/templates/tmux-colors.conf'
output_path = '~/.config/tmux/generated.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf'

[templates.yazi]
input_path = '~/.config/matugen/templates/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'
