music_directory    "~/Musique"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.cache/mpd/database"
state_file         "~/.cache/mpd/state"
sticker_file       "~/.cache/mpd/sticker.sql"

auto_update        "yes"

audio_output {
    type "pipewire"
    name "PipeWire"
}

input {
    plugin "curl"
}