#!/usr/bin/env bash
# Shared translation file for powermenu and confirmation scripts
# Detects locale and sets T_* variables for UI strings
# Fallback: English

_get_lang() {
  local lang="${LC_MESSAGES:-$LANG}"
  lang="${lang%%.*}"
  lang="${lang%%@*}"
  echo "${lang%%_*}"
}

_lang() {
  local lang
  lang="$(_get_lang)"
  case "$lang" in
    fr)
      T_POWEROFF="⏻ Éteindre"
      T_REBOOT="󰜉 Redémarrer"
      T_SUSPEND="⏾ Veille"
      T_LOCK="󰍁 Verrouiller"
      T_LOGOUT="󰗼 Déconnexion"
      T_UPTIME="Uptime"
      T_ARE_YOU_SURE="Êtes-vous sûr ?"
      T_YES="Oui"
      T_NO="Non"
      T_SHUT_DOWN="Éteindre ?"
      T_REBOOT_Q="Redémarrer ?"
      T_QUIT_HYPRLAND="Quitter Hyprland ?"
      T_UNSUPPORTED="Action non supportée"
      ;;
    es)
      T_POWEROFF="⏻ Apagar"
      T_REBOOT="󰜉 Reiniciar"
      T_SUSPEND="⏾ Suspender"
      T_LOCK="󰍁 Bloquear"
      T_LOGOUT="󰗼 Cerrar sesión"
      T_UPTIME="Uptime"
      T_ARE_YOU_SURE="¿Estás seguro?"
      T_YES="Sí"
      T_NO="No"
      T_SHUT_DOWN="¿Apagar?"
      T_REBOOT_Q="¿Reiniciar?"
      T_QUIT_HYPRLAND="¿Salir de Hyprland?"
      T_UNSUPPORTED="Acción no soportada"
      ;;
    de)
      T_POWEROFF="⏻ Ausschalten"
      T_REBOOT="󰜉 Neustart"
      T_SUSPEND="⏾ Bereitschaft"
      T_LOCK="󰍁 Sperren"
      T_LOGOUT="󰗼 Abmelden"
      T_UPTIME="Laufzeit"
      T_ARE_YOU_SURE="Bist du sicher?"
      T_YES="Ja"
      T_NO="Nein"
      T_SHUT_DOWN="Ausschalten?"
      T_REBOOT_Q="Neustart?"
      T_QUIT_HYPRLAND="Hyprland beenden?"
      T_UNSUPPORTED="Aktion nicht unterstützt"
      ;;
    it)
      T_POWEROFF="⏻ Spegni"
      T_REBOOT="󰜉 Riavvia"
      T_SUSPEND="⏾ Sospensione"
      T_LOCK="�1 Blocca"
      T_LOGOUT="󰗼 Disconnetti"
      T_UPTIME="Uptime"
      T_ARE_YOU_SURE="Sei sicuro?"
      T_YES="Sì"
      T_NO="No"
      T_SHUT_DOWN="Spegnere?"
      T_REBOOT_Q="Riavviare?"
      T_QUIT_HYPRLAND="Uscire da Hyprland?"
      T_UNSUPPORTED="Azione non supportata"
      ;;
    pt)
      T_POWEROFF="⏻ Desligar"
      T_REBOOT="�9 Reiniciar"
      T_SUSPEND="⏾ Suspender"
      T_LOCK="󰍁 Bloquear"
      T_LOGOUT="󰗼 Sair"
      T_UPTIME="Uptime"
      T_ARE_YOU_SURE="Tem certeza?"
      T_YES="Sim"
      T_NO="Não"
      T_SHUT_DOWN="Desligar?"
      T_REBOOT_Q="Reiniciar?"
      T_QUIT_HYPRLAND="Sair do Hyprland?"
      T_UNSUPPORTED="Ação não suportada"
      ;;
    ja)
      T_POWEROFF="⏻ シャットダウン"
      T_REBOOT="󰜉 再起動"
      T_SUSPEND="⏾ スリープ"
      T_LOCK="󰍁 ロック"
      T_LOGOUT="󰗼 ログアウト"
      T_UPTIME="稼働時間"
      T_ARE_YOU_SURE="よろしいですか？"
      T_YES="はい"
      T_NO="いいえ"
      T_SHUT_DOWN="シャットダウンしますか？"
      T_REBOOT_Q="再起動しますか？"
      T_QUIT_HYPRLAND="Hyprlandを終了しますか？"
      T_UNSUPPORTED="サポートされていない操作"
      ;;
    zh)
      T_POWEROFF="⏻ 关机"
      T_REBOOT="󰜉 重启"
      T_SUSPEND="⏾ 挂起"
      T_LOCK="󰍁 锁定"
      T_LOGOUT="󰗼 注销"
      T_UPTIME="运行时间"
      T_ARE_YOU_SURE="确定吗？"
      T_YES="是"
      T_NO="否"
      T_SHUT_DOWN="关机？"
      T_REBOOT_Q="重启？"
      T_QUIT_HYPRLAND="退出 Hyprland？"
      T_UNSUPPORTED="不支持的操作"
      ;;
    ko)
      T_POWEROFF="⏻ 종료"
      T_REBOOT="󰜉 재시작"
      T_SUSPEND="⏾ 절전"
      T_LOCK="󰍁 잠금"
      T_LOGOUT="󰗼 로그아웃"
      T_UPTIME="가동 시간"
      T_ARE_YOU_SURE="확실합니까?"
      T_YES="예"
      T_NO="아니오"
      T_SHUT_DOWN="종료하시겠습니까?"
      T_REBOOT_Q="재시작하시겠습니까?"
      T_QUIT_HYPRLAND="Hyprland를 종료하시겠습니까?"
      T_UNSUPPORTED="지원되지 않는 작업"
      ;;
    ru)
      T_POWEROFF="⏻ Выключение"
      T_REBOOT="󰜉 Перезагрузка"
      T_SUSPEND="⏾ Ждущий режим"
      T_LOCK="󰍁 Блокировка"
      T_LOGOUT="󰗼 Выход"
      T_UPTIME="Время работы"
      T_ARE_YOU_SURE="Вы уверены?"
      T_YES="Да"
      T_NO="Нет"
      T_SHUT_DOWN="Выключить?"
      T_REBOOT_Q="Перезагрузить?"
      T_QUIT_HYPRLAND="Выйти из Hyprland?"
      T_UNSUPPORTED="Неподдерживаемое действие"
      ;;
    ar)
      T_POWEROFF="⏻ إيقاف"
      T_REBOOT="�92 إعادة تشغيل"
      T_SUSPEND="⏾ إسبات"
      T_LOCK="󰍁 قفل"
      T_LOGOUT="󰗼 خروج"
      T_UPTIME="وقت التشغيل"
      T_ARE_YOU_SURE="هل أنت متأكد؟"
      T_YES="نعم"
      T_NO="لا"
      T_SHUT_DOWN="إيقاف التشغيل؟"
      T_REBOOT_Q="إعادة التشغيل؟"
      T_QUIT_HYPRLAND="الخروج من Hyprland؟"
      T_UNSUPPORTED="إجراء غير مدعوم"
      ;;
    nl)
      T_POWEROFF="⏻ Uitschakelen"
      T_REBOOT="󰜉 Herstarten"
      T_SUSPEND="⏾ Slaapstand"
      T_LOCK="󰍁 Vergrendelen"
      T_LOGOUT="󰗼 Afmelden"
      T_UPTIME="Uptime"
      T_ARE_YOU_SURE="Weet je het zeker?"
      T_YES="Ja"
      T_NO="Nee"
      T_SHUT_DOWN="Uitschakelen?"
      T_REBOOT_Q="Herstarten?"
      T_QUIT_HYPRLAND="Hyprland sluiten?"
      T_UNSUPPORTED="Niet-ondersteunde actie"
      ;;
    sv)
      T_POWEROFF="⏻ Stäng av"
      T_REBOOT="󰜉 Starta om"
      T_SUSPEND="⏾ Vila"
      T_LOCK="�1 Lås"
      T_LOGOUT="󰗼 Logga ut"
      T_UPTIME="Drifttid"
      T_ARE_YOU_SURE="Är du säker?"
      T_YES="Ja"
      T_NO="Nej"
      T_SHUT_DOWN="Stäng av?"
      T_REBOOT_Q="Starta om?"
      T_QUIT_HYPRLAND="Avsluta Hyprland?"
      T_UNSUPPORTED="Ej stödd åtgärd"
      ;;
    pl)
      T_POWEROFF="⏻ Wyłącz"
      T_REBOOT="󰜉 Restart"
      T_SUSPEND="⏾ Uśpij"
      T_LOCK="󰍁 Zablokuj"
      T_LOGOUT="󰗼 Wyloguj"
      T_UPTIME="Czas pracy"
      T_ARE_YOU_SURE="Na pewno?"
      T_YES="Tak"
      T_NO="Nie"
      T_SHUT_DOWN="Wyłączyć?"
      T_REBOOT_Q="Restartować?"
      T_QUIT_HYPRLAND="Zakończyć Hyprland?"
      T_UNSUPPORTED="Nieobsługiwane działanie"
      ;;
    tr)
      T_POWEROFF="⏻ Kapat"
      T_REBOOT="�9 Yeniden başlat"
      T_SUSPEND="⏾ Askıya al"
      T_LOCK="󰍁 Kilitle"
      T_LOGOUT="󰗼 Çıkış"
      T_UPTIME="Çalışma süresi"
      T_ARE_YOU_SURE="Emin misiniz?"
      T_YES="Evet"
      T_NO="Hayır"
      T_SHUT_DOWN="Kapatılsın mı?"
      T_REBOOT_Q="Yeniden başlatılsın mı?"
      T_QUIT_HYPRLAND="Hyprland'tan çıkılsın mı?"
      T_UNSUPPORTED="Desteklenmeyen işlem"
      ;;
    uk)
      T_POWEROFF="⏻ Вимкнення"
      T_REBOOT="�92 Перезавантаження"
      T_SUSPEND="⏾ Сплячий режим"
      T_LOCK="󰍁 Блокування"
      T_LOGOUT="󰗼 Вихід"
      T_UPTIME="Час роботи"
      T_ARE_YOU_SURE="Ви впевнені?"
      T_YES="Так"
      T_NO="Ні"
      T_SHUT_DOWN="Вимкнути?"
      T_REBOOT_Q="Перезавантажити?"
      T_QUIT_HYPRLAND="Вийти з Hyprland?"
      T_UNSUPPORTED="Непідтримувана дія"
      ;;
    cs)
      T_POWEROFF="⏻ Vypnout"
      T_REBOOT="󰜉 Restart"
      T_SUSPEND="⏾ Režim spánku"
      T_LOCK="󰍁 Zamknout"
      T_LOGOUT="󰗼 Odhlásit"
      T_UPTIME="Doba běhu"
      T_ARE_YOU_SURE="Jste si jisti?"
      T_YES="Ano"
      T_NO="Ne"
      T_SHUT_DOWN="Vypnout?"
      T_REBOOT_Q="Restartovat?"
      T_QUIT_HYPRLAND="Ukončit Hyprland?"
      T_UNSUPPORTED="Nepodporovaná akce"
      ;;
    hu)
      T_POWEROFF="⏻ Leállítás"
      T_REBOOT="󰜉 �jraindítás"
      T_SUSPEND="⏾ Alvó üzemmód"
      T_LOCK="󰍁 Zárolás"
      T_LOGOUT="󰗼 Kijelentkezés"
      T_UPTIME="Üzemidő"
      T_ARE_YOU_SURE="Biztos vagy benne?"
      T_YES="Igen"
      T_NO="Nem"
      T_SHUT_DOWN="Leállítás?"
      T_REBOOT_Q="Újraindítás?"
      T_QUIT_HYPRLAND="Kilépés a Hyprland-ből?"
      T_UNSUPPORTED="Nem támogatott művelet"
      ;;
    ro)
      T_POWEROFF="⏻ Oprire"
      T_REBOOT="�9 Repornire"
      T_SUSPEND="⏾ Repaus"
      T_LOCK="󰍁 Blocare"
      T_LOGOUT="󰗼 Deconectare"
      T_UPTIME="Timp de funcționare"
      T_ARE_YOU_SURE="Ești sigur?"
      T_YES="Da"
      T_NO="Nu"
      T_SHUT_DOWN="Oprire?"
      T_REBOOT_Q="Repornire?"
      T_QUIT_HYPRLAND="Ieșire din Hyprland?"
      T_UNSUPPORTED="Acțiune neacceptată"
      ;;
    el)
      T_POWEROFF="⏻ Τερματισμός"
      T_REBOOT="�9 Επανεκκίνηση"
      T_SUSPEND="⏾ Αναστολή"
      T_LOCK="�71 Κλείδωμα"
      T_LOGOUT="󰗼 Αποσύνδεση"
      T_UPTIME="Χρόνος λειτουργίας"
      T_ARE_YOU_SURE="Είσαι σίγουρος;"
      T_YES="Ναι"
      T_NO="Όχι"
      T_SHUT_DOWN="Τερματισμός;"
      T_REBOOT_Q="Επανεκκίνηση;"
      T_QUIT_HYPRLAND="Έξοδος από Hyprland;"
      T_UNSUPPORTED="Μη υποστηριζόμενη ενέργεια"
      ;;
    th)
      T_POWEROFF="⏻ ปิดเครื่อง"
      T_REBOOT="�9重启"
      T_SUSPEND="⏾ โหมดพัก"
      T_LOCK="󰍁 ล็อก"
      T_LOGOUT="󰗼 ออกจากระบบ"
      T_UPTIME="เวลาทำงาน"
      T_ARE_YOU_SURE="คุณแน่ใจหรือไม่?"
      T_YES="ใช่"
      T_NO="ไม่"
      T_SHUT_DOWN="ปิดเครื่อง?"
      T_REBOOT_Q="รีสตาร์ท?"
      T_QUIT_HYPRLAND="ออกจาก Hyprland?"
      T_UNSUPPORTED="การกระทำที่ไม่รองรับ"
      ;;
    vi)
      T_POWEROFF="⏻ Tắt"
      T_REBOOT="󰜉 Khởi động lại"
      T_SUSPEND="⏾ Ngủ đông"
      T_LOCK="󰍁 Khóa"
      T_LOGOUT="󰗼 Đăng xuất"
      T_UPTIME="Thời gian hoạt động"
      T_ARE_YOU_SURE="Bạn có chắc không?"
      T_YES="Có"
      T_NO="Không"
      T_SHUT_DOWN="Tắt máy?"
      T_REBOOT_Q="Khởi động lại?"
      T_QUIT_HYPRLAND="Thoát Hyprland?"
      T_UNSUPPORTED="Hành động không được hỗ trợ"
      ;;
    id)
      T_POWEROFF="⏻ Matikan"
      T_REBOOT="�9重启 Ulang"
      T_SUSPEND="⏾ Tidur"
      T_LOCK="�1 Kunci"
      T_LOGOUT="󰗼 Keluar"
      T_UPTIME="Waktu aktif"
      T_ARE_YOU_SURE="Apakah Anda yakin?"
      T_YES="Ya"
      T_NO="Tidak"
      T_SHUT_DOWN="Matikan?"
      T_REBOOT_Q="Mulai ulang?"
      T_QUIT_HYPRLAND="Keluar dari Hyprland?"
      T_UNSUPPORTED="Aksi tidak didukung"
      ;;
    hi)
      T_POWEROFF="⏻ बंद करें"
      T_REBOOT="󰜉 पुनरारंभ"
      T_SUSPEND="⏾ निलंबन"
      T_LOCK="󰍁 लॉक"
      T_LOGOUT="󰗼 लॉग आउट"
      T_UPTIME="अपटाइम"
      T_ARE_YOU_SURE="क्या आप सुनिश्चित हैं?"
      T_YES="हाँ"
      T_NO="नहीं"
      T_SHUT_DOWN="बंद करें?"
      T_REBOOT_Q="पुनरारंभ करें?"
      T_QUIT_HYPRLAND="Hyprland से बाहर निकलें?"
      T_UNSUPPORTED="असमर्थित क्रिया"
      ;;
    fa)
      T_POWEROFF="⏻ خاموش کردن"
      T_REBOOT="󰜉 راه‌اندازی مجدد"
      T_SUSPEND="⏾ خواب"
      T_LOCK="󰍁 قفل"
      T_LOGOUT="󰗼 خروج"
      T_UPTIME="زمان کارکرد"
      T_ARE_YOU_SURE="مطمئن هستید؟"
      T_YES="بله"
      T_NO="خیر"
      T_SHUT_DOWN="خاموش شود؟"
      T_REBOOT_Q="راه‌اندازی مجدد شود؟"
      T_QUIT_HYPRLAND="خروج از Hyprland؟"
      T_UNSUPPORTED="عملیات پشتیبانی نشده"
      ;;
    he)
      T_POWEROFF="⏻ כיבוי"
      T_REBOOT="�92 אתחול"
      T_SUSPEND="⏾ שינה"
      T_LOCK="󰍁 נעילה"
      T_LOGOUT="󰗼 התנתקות"
      T_UPTIME="זמן פעילות"
      T_ARE_YOU_SURE="אתה בטוח?"
      T_YES="כן"
      T_NO="לא"
      T_SHUT_DOWN="כיבוי?"
      T_REBOOT_Q="אתחול?"
      T_QUIT_HYPRLAND=" יציאה מ-Hyprland?"
      T_UNSUPPORTED="פעולה לא נתמכת"
      ;;
    ga)
      T_POWEROFF="�1 Muir"
      T_REBOOT="󰜉 Atosaí"
      T_SUSPEND="⏾ Sosaint"
      T_LOCK="󰍁 Glasáil"
      T_LOGOUT="�1 Logáil amach"
      T_UPTIME="Am feidhme"
      T_ARE_YOU_SURE="An bhfuil tú cinnte?"
      T_YES="Tá"
      T_NO="Níl"
      T_SHUT_DOWN="Dúnadh?"
      T_REBOOT_Q="Atosaí?"
      T_QUIT_HYPRLAND="Scoir de Hyprland?"
      T_UNSUPPORTED="Gníomh gan tacaíocht"
      ;;
    ka)
      T_POWEROFF="⏻ გამორთვა"
      T_REBOOT="󰜉 გადატვირთვა"
      T_SUSPEND="⏾ ძილი"
      T_LOCK="�71 დაბლოკვა"
      T_LOGOUT="󰗼 გასვლა"
      T_UPTIME="მუშაობის დრო"
      T_ARE_YOU_SURE="დარწმუნებული ხარ?"
      T_YES="დიახ"
      T_NO="არა"
      T_SHUT_DOWN="გამორთვა?"
      T_REBOOT_Q="გადატვირთვა?"
      T_QUIT_HYPRLAND="Hyprland-დან გასვლა?"
      T_UNSUPPORTED="მხარდაუჭერელი მოქმედება"
      ;;
    *)
      T_POWEROFF="⏻ Poweroff"
      T_REBOOT="󰜉 Reboot"
      T_SUSPEND="⏾ Suspend"
      T_LOCK="󰍁 Lock"
      T_LOGOUT="󰗼 Logout"
      T_UPTIME="Uptime"
      T_ARE_YOU_SURE="Are you sure?"
      T_YES="Yes"
      T_NO="No"
      T_SHUT_DOWN="Shut down?"
      T_REBOOT_Q="Reboot?"
      T_QUIT_HYPRLAND="Quit Hyprland?"
      T_UNSUPPORTED="Unsupported action"
      ;;
  esac
}

_lang
