# Mouse
set -g mouse on

# Source matugen
source-file ~/.config/tmux/generated.conf

# tmux-agent-sidebar
set -g @plugin 'hiroppy/tmux-agent-sidebar'
set -g @sidebar_auto_create off

# TPM
run '~/.tmux/plugins/tpm/tpm'
