source = $HOME/.config/hypr/colors.conf

$font = JetBrainsMono Nerd Font

general {
  disable_loading_bar = true
  hide_cursor = true
}

background {
  monitor =
  path = screenshot
  blur_passes = 2
  color = $surface_dim
}

label {
  monitor =
  text = Layout: $LAYOUT
  color = $on_surface
  font_size = 10
  font_family = $font
  position = 10, 10
  halign = left
  valign = bottom
}

label {
  monitor =
  text = $TIME
  color = $on_surface
  font_size = 24
  font_family = $font
  position = -10, 25
  halign = right
  valign = bottom
}

label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = $on_surface
  font_size = 10
  font_family = $font
  position = -10, 10
  halign = right
  valign = bottom
}

image {
  monitor =
  path = $HOME/.face
  size = 150
  border_color = $primary
  border_size = 3
  position = 0, 75
  halign = center
  valign = center
}

input-field {
  monitor =
  size = 300, 35
  outline_thickness = 2
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = $primary
  inner_color = $surface
  font_color = $on_surface
  fade_on_empty = false
  placeholder_text = <span foreground="##$on_surface_hex_stripped"><i>󰌾 Logged in as </i><span foreground="##$primary_hex_stripped">$USER</span></span>
  hide_input = false
  check_color = $primary
  fail_color = $error
  fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
  capslock_color = $tertiary
  position = 0, -50
  halign = center
  valign = center
}
